---
output:
  pdf_document: default
  html_document: default
---
`r if (knitr::is_html_output()) '
# References 
'`

- [City of Vancouver Solution Lab’s Principles of Experimentation](https://vancouver.ca/files/cov/navigating-complexity-solutions-lab.pdf), adapted from [Nesta’s Innovation Playbook](https://www.nesta.org.uk/toolkit/playbook-for-innovation-learning/)  

- [Nesta’s Competency Framework for Experimental Problem Solving](https://media.nesta.org.uk/documents/Nesta_CompetencyFramework_Guide_July2019.pdf) 

- [States of Change’s Core Elements of Innovation](https://states-of-change.org/assets/images/StatesofChange_Curriculum_Craft.png)    

- [Tatyana Mamut’s eight Innovation Elements](https://gww.gov.bc.ca/sites/default/files/group/file/2019/0207/remixtatyanamamutleadingacultureofinnovationlowres.pdf) 

- [The Moment’s Culture Scan](https://info.themoment.is/innovationculture) 

- [Innovation Designer Capability Map](https://cdn2.hubspot.net/hubfs/3903042/themoment_InnovationDesignersCapabilityMap.pdf) 

- [Alliance for useful evidence](https://www.alliance4usefulevidence.org/)

- [Better public services through experimental government](https://www.alliance4usefulevidence.org/publication/better-public-services-through-experimental-government/)

- [The What Works Trial Advice Panel](https://www.gov.uk/government/publications/cross-government-trial-advice-panel-role-and-membership)

- [Integrated Communities Strategy green paper](https://www.gov.uk/government/consultations/integrated-communities-strategy-green-paper)

- [The impact of Sure Start Local Programmes on seven year olds and their families](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/495329/The_impact_of_Sure_Start_local_programmes_on_7-year-olds_and_their_families.pdf)

- [National Evaluation of the Troubled Families Programme 2015 - 2020](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/786891/National_evaluation_of_the_Troubled_Families_Programme_2015_to_2020_family_outcomes___national_and_local_datasets_part_4.pdf)

- [Social Media and Fake News in the 2016 Election](https://pubs.aeaweb.org/doi/pdfplus/10.1257/jep.31.2.211)

- [Reflections on the Ethics of Social Experimentation](https://www.degruyter.com/view/journals/jgd/6/1/article-p87.xml)

- [From Research Topic to Research Question](https://us.sagepub.com/sites/default/files/upm-assets/72299_book_item_72299.pdf)

- [Facilitating Complex Multi-Stakeholder Processes, A Social Learning Perspective](http://library.enaca.org/mangrove/publications/Woodhill_Facilitating_MSP.pdf)